Algoritmo "etec-141-pa-consumogas"
// Disciplina: PA
// Professora: Edilma Bindá
// Turma: 1°C / B
// Nome: Luiggy Pezini Garcia
// Data: 07/04/2023

Var
percorrido: real
consumo: real
preco: real
Inicio
escreval("Consumo: percorrido, consumido, preço do litro")
leia(percorrido, consumo, preco)
escreval("Total: ", percorrido/consumo*preco)
escreval("Ida e volta: ", (percorrido/consumo*preco)*2)
Fimalgoritmo