Algoritmo "etec-141-pa-cond-e4"
// Disciplina: PA
// Professora: Edilma Bindá
// Turma: 1° C / B
// Nome: Luiggy Pezini Garcia
// Data: 25/05/2023
Var
nome: caractere
n1: real
n2: real
n3: real
n4: real
Inicio
escreval("Nome, nota 1, n2, n3, n4: ")
leia(nome, n1, n2, n3, n4)
se (n1+n2+n3+n4)/4 >= 7 entao
escreval(nome, " está aprovado.")
senao
escreval(nome, " está reprovado.")
fimse

Fimalgoritmo